/**
 * Starting a curated plan.
 *
 * A curated plan is a TEMPLATE on a shelf. Starting one takes a copy — it does
 * not subscribe to it. From that moment the week belongs to the person: they
 * can swap a movement, change the numbers, duplicate a day, and none of it
 * touches the original. Equally, if the curated plan is later corrected or
 * retired, their week does not change under them halfway through.
 *
 * WHAT MUST NOT COME ACROSS. The template carries nothing personal, and the
 * copy must not invent any: no completion state, no start date from the
 * template, no id. This is the same rule that keeps shopping-list ticks from
 * travelling with a duplicated plan — a stranger's progress is not your
 * progress, and a plan that arrives claiming three sessions are already done
 * is worse than no plan.
 *
 * WHAT IS DELIBERATELY NOT DONE. The plan is copied EXACTLY. It is not adapted
 * to the profile on the way in, even though we know their injuries and their
 * equipment. Three reasons: adapting silently means nobody ever gets the plan
 * that was actually tested; it would cost credits, and free-on-day-one is the
 * whole premise; and the builder ALREADY warns about contraindications and
 * missing kit, with swap one tap away. Tell them, let them choose.
 */
import type { HealthPlan, HealthPlanDay } from './health-types';

/** A row from /api/health/curated-plans. */
export interface CuratedPlanSummary {
  id: string;
  title: string;
  summary: string | null;
  type: 'fitness' | 'meal' | 'combined';
  goal: string | null;
  level: string | null;
  duration_days: number;
  days_per_week: number | null;
  minutes_per_session: number | null;
  tags: string[];
  equipment: string[];
  cover_image_url: string | null;
  start_count: number;
}

export interface CuratedPlanDetail extends CuratedPlanSummary {
  description: string | null;
  days: HealthPlanDay[];
}

/**
 * Strip a template day back to something nobody has touched.
 *
 * Guards against the template having picked up state it should never hold —
 * a draft that was started from an existing plan in the Hub, say. Cheap
 * insurance against a class of bug that would be invisible until someone
 * opened a brand-new plan and found Tuesday already ticked off.
 */
function cleanDay(day: HealthPlanDay, index: number): HealthPlanDay {
  return {
    day_index: index,
    kind: day?.kind === 'training' || day?.kind === 'active_recovery' ? day.kind : 'rest',
    title: day?.title ?? null,
    training: Array.isArray(day?.training) ? day.training : [],
    meals: Array.isArray(day?.meals) ? day.meals : [],
    notes: day?.notes ?? null,
    // Never inherited — always a fresh start.
    completion: null,
  } as HealthPlanDay;
}

export interface StartOptions {
  /** Defaults to today. Present so back-dating and tests are possible. */
  startDate: string;
  /** Generated by the caller, so this stays pure. */
  id: string;
  now?: string;
}

/**
 * Build the local plan a person actually gets.
 *
 * Lands ACTIVE rather than as a draft: the promise is a good week on day one,
 * and a starter sitting in drafts helps nobody. That is only fair because the
 * browse sheet shows the whole plan before the button is pressed — starting is
 * an informed act, not a blind one.
 */
export function planFromCurated(
  curated: CuratedPlanDetail,
  opts: StartOptions,
): HealthPlan {
  const now = opts.now ?? new Date().toISOString();
  const duration = Math.max(1, Number(curated.duration_days) || 1);
  const source = Array.isArray(curated.days) ? curated.days : [];

  // Index by day_index rather than array position: a template with days out of
  // order should not produce a shuffled week.
  const byIndex = new Map<number, HealthPlanDay>();
  for (const d of source) {
    if (d && typeof d.day_index === 'number') byIndex.set(d.day_index, d);
  }

  const days: HealthPlanDay[] = Array.from({ length: duration }, (_, i) => {
    const found = byIndex.get(i + 1);
    return found
      ? cleanDay(found, i + 1)
      : cleanDay({ day_index: i + 1, kind: 'rest', title: null, training: [], meals: [], notes: null } as HealthPlanDay, i + 1);
  });

  return {
    schema_version: 1,
    id: opts.id,
    type: curated.type,
    title: curated.title,
    goal: curated.goal,
    // Its own provenance. "Ava wrote this for you" and "this is a
    // professionally built starter" are different claims and a plan card
    // should not show them identically.
    source: 'curated',
    status: 'active',
    duration_days: duration,
    start_date: opts.startDate,
    // The template has no profile behind it — it was written for strangers.
    // Claiming a snapshot would be inventing one.
    profile_snapshot: null,
    days,
    created_at: now,
    updated_at: now,
  } as HealthPlan;
}

/**
 * Order the shelf for THIS person.
 *
 * Their stated goal first, then whatever others exist. Not a filter: someone
 * whose profile says muscle gain should still be able to see the recovery
 * week, because the reason they need it may be the reason they stopped
 * training. Sorting answers "what is most likely for you" without hiding
 * anything.
 */
export function orderForProfile(
  plans: CuratedPlanSummary[],
  primaryGoal: string | null,
): CuratedPlanSummary[] {
  if (!primaryGoal) return plans;
  return [...plans].sort((a, b) => {
    const am = a.goal === primaryGoal ? 0 : 1;
    const bm = b.goal === primaryGoal ? 0 : 1;
    return am - bm;
  });
}

/** "3 days · 2 sessions" — what the week actually asks of you, counted from
 *  the plan rather than from what it claims about itself. */
export function shapeOf(days: HealthPlanDay[]): { training: number; rest: number; exercises: number } {
  let training = 0, rest = 0, exercises = 0;
  for (const d of days ?? []) {
    if ((d?.training?.length ?? 0) > 0) training++; else rest++;
    exercises += d?.training?.length ?? 0;
  }
  return { training, rest, exercises };
}
