// -----------------------------------------------------------------------------
// GENERATED FILE — do not edit directly.
// Source of truth: packages/core/src/docs/
// Run  pnpm docs:sync  from the repo root to regenerate.
// -----------------------------------------------------------------------------

import type { DocPage } from '../types';

// Section 4 — Features. Chunkable. Each page is a self-contained feature description.

export const FEATURE_PAGES: DocPage[] = [
  {
    id: 'features.unified-panel',
    title: 'Unified panel',
    audience: ['both'],
    surfaces: ['ext', 'ide'],
    order: 10,
    section: 'features',
    body: [
      { type: 'paragraph', text: 'In plain terms: everything Ava does lives in one window, so you never go hunting through tabs to find it.' },
      { type: 'paragraph', text: 'One panel for chat, dashboard, memory, tasks, and journal. No context switching between windows. The sidebar picks what you are looking at; the main area swaps to match.' },
      { type: 'paragraph', text: 'Conversation state persists when you navigate away — open memory, check a task, then come back. The chat is still there, still streaming if Ava is still running.' },
      { type: 'callout', variant: 'note', text: 'Unified panel is an extension and IDE concept. The web surface uses browser tabs.' },
    ],
  },
  {
    id: 'features.knowledge-packs',
    title: 'Knowledge packs',
    audience: ['both'],
    surfaces: ['web', 'ext', 'ide'],
    order: 20,
    section: 'features',
    body: [
      { type: 'paragraph', text: 'In plain terms: hand Ava a folder of your own documents, and she can read from them to answer your questions. A "knowledge pack" is just that bundle of files — your reference material she is allowed to draw on.' },
      { type: 'paragraph', text: 'Drop a directory of reference material (specs, RFCs, meeting notes, API docs) into a knowledge pack. Ava can pull the relevant pieces into context when a conversation touches the topic.' },
      { type: 'paragraph', text: 'Packs are indexed locally. Retrieval is semantic — Ava finds the right document by meaning, not filename. ("Semantic" means she matches on what a document is about, so you do not need to remember the exact words or the file name.) Packs can be shared with a team or kept private.' },
    ],
  },
  {
    id: 'features.creative-studio',
    title: 'Creative Studio',
    audience: ['both'],
    surfaces: ['web', 'ext', 'ide'],
    order: 30,
    section: 'features',
    body: [
      { type: 'paragraph', text: 'In plain terms: describe the icon, image, video, or voiceover you want, and Ava designs it with you — no design software, no prompt-wrangling.' },
      { type: 'paragraph', text: 'Creative Studio is a guided design workspace. It opens in three panes — the design types down the left, your canvas in the middle, and the controls for the piece you are working on down the right. There is no "generate" button to hunt for: you talk to the Design Architect (Ava, in her designer role) at the bottom of the screen, she runs the tools for you, and you refine with a few clear controls.' },
      { type: 'heading', level: 3, text: 'What you can make today' },
      { type: 'list', ordered: false, items: [
        'Icons — the flagship. Start from a real line-icon shape (1,990 built in), choose a material and your brand colour, and Ava restyles it and cuts it to a clean transparent PNG.',
        'Images — free-form, from a description. Square, landscape, or portrait (1:1, 16:9, 9:16).',
        'Video — short AI clips from a prompt. 5 or 10 seconds, up to 1080p, in landscape, portrait, or square.',
        'Voiceovers — text to natural speech, with a waveform preview. Ten voices across ten languages.',
        'Brand Kit — your palette, kept to hand so every asset stays on-brand.',
      ]},
      { type: 'paragraph', text: 'More design types — app icons, logos, badges, avatars, banners, hero and social images, illustrations, patterns, and a full game-dev set — are being brought over, and show as "soon" in the left rail.' },
      { type: 'heading', level: 3, text: 'What powers it' },
      { type: 'paragraph', text: 'Icons and images are generated with Qwen-Image, video with Wan, and voiceovers with Qwen3-TTS. Anything you make lands in your Library, filed under the type you made it in.' },
      { type: 'paragraph', text: 'Creative Studio is not a paid add-on — it is available on every plan, Free included. Generations draw from your normal credit pool, the same one number as the rest of Ava.' },
      { type: 'callout', variant: 'note', text: 'Music is not part of Creative Studio right now — icons, images, video, and voiceovers are. (The old image/music/voice "Compose" surface has been retired into this one workspace.)' },
    ],
  },
  {
    id: 'features.health',
    title: 'Health & Nutrition',
    audience: ['both'],
    surfaces: ['web', 'ext', 'ide'],
    order: 35,
    section: 'features',
    body: [
      { type: 'paragraph', text: 'In plain terms: tell Ava your goal and what you have to work with, and she builds you a real workout and meal plan — then helps you follow it, day by day.' },
      { type: 'paragraph', text: 'Health & Nutrition is a focused room in the dashboard. Ava asks a few things about you — your goal, your equipment, any limits — then draws on a real library of exercises and recipes to build a plan that fits. Plans can be fitness, meal, or both together.' },
      { type: 'heading', level: 3, text: 'How it works' },
      { type: 'list', ordered: true, items: [
        'Ava asks about your goal and setup through simple controls — goal cards, equipment chips, a number box — not a wall of questions.',
        'She builds a multi-week plan from the catalogue, one you can actually do with what you have.',
        'You follow it day by day; Ava can fill in or adjust any single day as things change.',
      ]},
      { type: 'paragraph', text: 'Everything is saved to your local plan library, on your own machine. The recipe and exercise catalogues are real, curated content — not made up on the fly.' },
      { type: 'callout', variant: 'note', text: 'Health & Nutrition is general guidance, not medical advice. Plans come from a general library — check with a professional for anything medical.' },
    ],
  },
  {
    id: 'features.learning',
    title: 'Learning',
    audience: ['both'],
    surfaces: ['web', 'ext', 'ide'],
    order: 37,
    section: 'features',
    body: [
      { type: 'paragraph', text: 'In plain terms: ask Ava to teach you something and she builds you a proper course — lessons, worked examples, and quizzes — then walks you through it at your own pace.' },
      { type: 'paragraph', text: 'Learning is a focused room in the dashboard. Ava plans a curriculum for what you want to learn, teaches it lesson by lesson, checks your understanding with quizzes, and tracks what you have covered so you can pick up where you left off.' },
      { type: 'heading', level: 3, text: 'How it works' },
      { type: 'list', ordered: true, items: [
        'Tell Ava a topic — "teach me Python from scratch", or "help me understand databases".',
        'She builds a structured course: modules, lessons, and checkpoints.',
        'You learn one lesson at a time; she explains, gives examples, and quizzes you to make it stick.',
        'Your progress is saved, so the next session starts where you stopped.',
      ]},
      { type: 'paragraph', text: 'Underneath, this is Teach mode — a small team of specialists (a curriculum architect, a content writer, a fact checker, a quiz master, and a tutor) that Ava coordinates for you.' },
      { type: 'callout', variant: 'tip', text: 'No experience needed — Learning is written for complete beginners as much as for people brushing up.' },
    ],
  },
  {
    id: 'features.office-suite',
    title: 'Office Suite',
    audience: ['both'],
    surfaces: ['web', 'ext', 'ide', 'companion'],
    order: 40,
    section: 'features',
    body: [
      { type: 'paragraph', text: 'Need a report, an email, or a document written up? Ava can draft it and hand you a real Word, Excel, or PDF file you can open and edit like any other.' },
      { type: 'paragraph', text: 'Reports, emails, and documents — drafted, formatted, and exported to native formats (.docx is Word, .xlsx is Excel, .pdf is a PDF).' },
      { type: 'list', ordered: false, items: [
        'report_generate — a structured .docx pulling from tasks, journal, memory, and project state.',
        'email_draft — tone-controlled email to a .docx file.',
        'document_manage — create, read, edit, export across Word, Excel, PDF, CSV, Markdown.',
      ]},
      { type: 'paragraph', text: 'Useful when Ava is writing on your behalf — status reports, kickoff decks, client updates. The .docx lands in your project where you can polish it.' },
    ],
  },
  {
    id: 'features.dashboard-library',
    title: 'Library',
    audience: ['both'],
    surfaces: ['web', 'ext', 'ide'],
    order: 50,
    section: 'features',
    body: [
      { type: 'paragraph', text: 'In plain terms: one shelf for the things you keep — the papers you are reading, the assets you have made, and the documents you have written — so nothing gets lost.' },
      { type: 'paragraph', text: 'The Library is a browsable dashboard with three tabs:' },
      { type: 'list', ordered: false, items: [
        'Papers — scientific papers you have saved, fetched from arXiv, OpenAlex, and Crossref, with the full text to read inline.',
        'Assets — everything you have made in Creative Studio, sorted by the same design types you made them in (Open Canvas, Web / App, Game Dev). Filter by group, then by type; each type shows how many you have.',
        'Documents — the Word, Excel, PDF, and other files Ava has written with you, filterable by where they live (local or synced) and what they are.',
      ]},
      { type: 'paragraph', text: 'A storage bar across the top shows how much space your local files use, and an "Open save folder" button drops you straight into the folder on disk. It is local-first — the Library reads what is on your own machine.' },
    ],
  },
  {
    id: 'features.document-preview',
    title: 'Document preview',
    audience: ['both'],
    surfaces: ['ext', 'ide'],
    requires: ['live_doc_preview'],
    order: 60,
    section: 'features',
    body: [
      { type: 'paragraph', text: 'In plain terms: peek inside a document right where you are, without opening a separate program to read it.' },
      { type: 'paragraph', text: 'Right-click a Word doc, Excel sheet, PDF, CSV, HTML, or Markdown file in your project — preview it inline without leaving the editor. Useful for reading reference material Ava has generated or files a collaborator dropped in.' },
    ],
  },
  {
    id: 'features.storage',
    title: 'Local storage',
    audience: ['both'],
    surfaces: ['ext', 'ide'],
    order: 55,
    section: 'features',
    body: [
      { type: 'paragraph', text: 'In plain terms: because Ava keeps your work on your own machine, she also shows you exactly how much space it is using — and helps you get some back when you need it.' },
      { type: 'paragraph', text: 'A storage bar in the Command Centre and the Library breaks your whole ~/.ava footprint down by category — Models, Runtime, Creative, Memory, Journal, Datasets, Old backups, and Other — so you can see where the space goes at a glance, and open the folder on disk in one click.' },
      { type: 'heading', level: 3, text: 'Reclaiming space' },
      { type: 'paragraph', text: 'Old migration backups build up quietly over time. When you want the space back, the storage view lets you clear just those old backups in two taps — and it will only ever remove items inside your Ava folder whose name marks them as a backup, so nothing else can be touched.' },
      { type: 'callout', variant: 'note', text: 'Measuring your footprint only reads folder names and file sizes — never the contents of your files. And it is all local: nothing is uploaded to produce these numbers.' },
    ],
  },
  {
    id: 'features.daily-briefing',
    title: 'Daily briefing',
    audience: ['both'],
    surfaces: ['web', 'ext', 'ide', 'companion'],
    order: 70,
    section: 'features',
    body: [
      { type: 'paragraph', text: 'In plain terms: a short "here is where you left off" note each morning, so you can pick up without rereading everything.' },
      { type: 'paragraph', text: 'Morning summary: yesterday journal, open tasks, project state, and any reminders Ava has set. Optional — turn it on in settings.' },
      { type: 'paragraph', text: 'The briefing uses memory to surface relevant context ("last time you worked on the auth flow, you noted you wanted to revisit the refresh token strategy"). Not a news feed — a focused catch-up.' },
    ],
  },
  {
    id: 'features.workflows',
    title: 'Workflows',
    audience: ['both'],
    surfaces: ['web', 'ext', 'ide'],
    order: 80,
    section: 'features',
    body: [
      { type: 'paragraph', text: 'In plain terms: teach Ava a routine you do over and over, give it a name, and she can run the whole thing again on demand. A "workflow" is just that saved routine — a set of steps Ava repeats for you.' },
      { type: 'paragraph', text: 'Save a sequence of steps you find yourself repeating — review PR → run tests → write release notes → draft the email. A workflow is a reusable plan Ava can replay with different inputs.' },
      { type: 'paragraph', text: 'Workflows are stored per project in a folder named .ava/workflows/ inside your project. Share them with your team by committing the directory (saving it into your shared project so teammates get it too).' },
    ],
  },
  {
    id: 'features.events',
    title: 'Events and notifications',
    audience: ['power'],
    surfaces: ['web', 'ext', 'ide', 'companion'],
    order: 90,
    section: 'features',
    body: [
      { type: 'paragraph', text: 'In plain terms: while Ava works you get a tidy step-by-step list of what she is doing, and a ping when a long job finishes so you can step away.' },
      { type: 'paragraph', text: 'While Ava is running you see structured updates, not a wall of text. Each tool call, each persona handoff, each streamed delta is a discrete event in the UI — expandable for detail, collapsible for overview.' },
      { type: 'paragraph', text: 'Background runs emit OS-level notifications when they complete. You can walk away from a long build and Ava will tell you when it is done.' },
    ],
  },
  {
    id: 'features.personality',
    title: 'Personality Designer',
    audience: ['both'],
    surfaces: ['web', 'ext', 'ide', 'companion'],
    order: 100,
    section: 'features',
    body: [
      { type: 'paragraph', text: 'In plain terms: dial in how Ava talks to you — chatty or brief, formal or casual, more jokes or fewer — so she sounds the way you like.' },
      { type: 'paragraph', text: 'Shape how Ava talks to you. Tone, energy, verbosity (how much she says), formality, humour. Sliders and presets — terse engineer, warm mentor, dry colleague, or your own blend.' },
      { type: 'paragraph', text: 'Personality affects phrasing, not competence. She still runs the same tools and follows the same permission rules. Her name is locked to Ava — that is non-negotiable.' },
    ],
  },
  {
    id: 'features.release-notes',
    title: 'Release notes',
    audience: ['both'],
    surfaces: ['ext', 'ide'],
    order: 110,
    section: 'features',
    body: [
      { type: 'paragraph', text: 'In plain terms: a running list of what is new and what got fixed in each update, so you can see what changed.' },
      { type: 'paragraph', text: 'In-app changelog (a changelog is the history of changes). Every shipped version with its highlights, bug fixes, and breaking changes (changes that may require you to adjust how you use something). The web surface maintains the public version at avasupernova.com/releases.' },
    ],
  },
  {
    id: 'features.desktop-automation',
    status: 'preview',
    title: 'Desktop Automation',
    audience: ['both'],
    surfaces: ['web', 'ext', 'ide', 'companion'],
    requires: ['desktop_automation'],
    order: 120,
    section: 'features',
    body: [
      { type: 'paragraph', text: 'In plain terms: Ava can take over your mouse and keyboard to do tasks for you — open an app, click buttons, fill in a form — while you watch and approve anything important.' },
      { type: 'paragraph', text: 'A new mode for Ava, prefix @@. She observes the desktop, decides what to do, and drives UI automation (controlling the apps on your screen for you) to get it done. Runs on your actual machine with your actual credentials — not a cloud browser. Available on every tier once shipped.' },
      { type: 'heading', level: 3, text: 'Why another one' },
      { type: 'paragraph', text: 'Every other desktop-automation product is something you start when you\'re at your desk. Ava is the one that\'s still there when your error tracker fires at 2am — IDE keeps running, your phone pairs over a secure channel, you approve irreversibles with a tap.' },
      { type: 'paragraph', text: 'She also remembers how to navigate your apps across sessions. Every other agent relearns them every time. The memory differentiator compounds with use.' },
      { type: 'heading', level: 3, text: 'How it works' },
      { type: 'paragraph', text: 'Each step runs a five-persona wave: Scout observes, Planner picks the next action, Actor executes, Verifier checks, Narrator tells you what happened. The sidecar chooses the cheapest reliable grounding — UIA for native apps, Playwright for browsers, OmniParser vision when nothing else has a useful tree.' },
      { type: 'paragraph', text: 'See the concepts pages for safety ontology, grounding hierarchy, kill switches, and the session whitelist model.' },
    ],
  },
];
